language: c

sudo: required

services:
  - docker

branches:
  only:
    - master
    - staging
    - develop
    - /^[a-z]{1,20}:[0-9]{12}$/

before_install:
  - export PROJECT=${TRAVIS_TAG%%:*}
  - echo $PROJECT
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - echo $TRAVIS_PULL_REQUEST
  - CHANGES=$(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master))
  - echo $CHANGES
  - cd $PROJECT && make login



notifications:
  email:
    recipients:
      - ssemichev@gmail.com
    on_success: always
    on_failure: always
