language: c

sudo: required

services:
  - docker

branches:
  only:
    - master
    - staging
    - develop
	- /^[a-z]{1,20}:[0-9]{12}$/

before_install:
  - export PROJECT=${TRAVIS_TAG%%:*}

  
notifications:
  email:
    recipients:
      - ssemichev@gmail.com
    on_success: always
    on_failure: always
