language: c

sudo: required

services:
  - docker

branches:
  only:
    - master
    - staging
    - develop

before_install:
  - SET PROJECT=scala-alpine
  - $(PROJECT)/make login

script:
  - echo $(PROJECT)

notifications:
  email:
    recipients:
      - ssemichev@gmail.com
    on_success: always
    on_failure: always
