language: c

sudo: required

services:
  - docker

branches:
  only:
    - master
    - staging
    - develop
    - /^[a-z]{1,20}:[0-9]{12}$/

before_install:
  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

script:
  - ./scripts/script-phase.rb

notifications:
  email:
    recipients:
      - ssemichev@gmail.com
    on_success: always
    on_failure: always
