language: c

sudo: required

services:
  - docker

branches:
  only:
    - master
    - staging
    - develop

before_install:
  - export PROJECT=scala-alpine
  - cd $PROJECT && make login

script:
  - make lint

notifications:
  email:
    recipients:
      - ssemichev@gmail.com
    on_success: always
    on_failure: always
